import type { Entity, ImpactTag, Legislation } from "@/types";

import netherlands from "@/data/international/netherlands.json";
import ireland from "@/data/international/ireland.json";
import sweden from "@/data/international/sweden.json";
import finland from "@/data/international/finland.json";
import spain from "@/data/international/spain.json";
import italy from "@/data/international/italy.json";
import poland from "@/data/international/poland.json";
import singapore from "@/data/international/singapore.json";
import india from "@/data/international/india.json";
import taiwan from "@/data/international/taiwan.json";
import indonesia from "@/data/international/indonesia.json";
import australia from "@/data/international/australia.json";

/**
 * Auto-generated by scripts/sync/international.ts. Do not edit by hand.
 * Entries come from data/international/*.json. Regenerated after every
 * successful sync run.
 *
 * This file also sanitizes incoming research payloads because Claude
 * sometimes invents impactTags outside our enum — we filter those out
 * rather than let the UI crash on unknown keys.
 */

const VALID_IMPACT_TAGS = new Set<ImpactTag>([
  "affordability",
  "environmental-review",
  "public-land",
  "environmental-review",
  "transit-oriented",
  "density",
  "mortgage-regulation",
  "social-housing",
  "community-opposition",
  "inclusionary-zoning",
  "nimby",
  "displacement",
  "affordability",
  "vacancy-tax",
  "first-time-buyer",
  "density",
  "heritage-protection",
  "rent-stabilization",
  "homelessness",
  "short-term-rental",
  "social-housing",
  "displacement",
  "indigenous-housing",
  "community-opposition",
  "foreign-buyer",
]);

function sanitizeLegislation(l: Legislation): Legislation {
  return {
    ...l,
    impactTags: (l.impactTags ?? []).filter((t): t is ImpactTag =>
      VALID_IMPACT_TAGS.has(t as ImpactTag),
    ),
  };
}

function sanitizeEntity(e: Entity): Entity {
  return {
    ...e,
    legislation: (e.legislation ?? []).map(sanitizeLegislation),
    keyFigures: e.keyFigures ?? [],
    news: e.news ?? [],
  };
}

const modules: Entity[] = [];
function register(mod: unknown) {
  if (mod && typeof mod === "object" && "id" in (mod as Record<string, unknown>)) {
    modules.push(sanitizeEntity(mod as Entity));
  }
}

register(netherlands);
register(ireland);
register(sweden);
register(finland);
register(spain);
register(italy);
register(poland);
register(singapore);
register(india);
register(taiwan);
register(indonesia);
register(australia);

export const RESEARCHED_INTERNATIONAL: Entity[] = modules;
