"use client";

import {
  ComposableMap,
  Geographies,
  Geography,
  type ProjectionFunction,
} from "react-simple-maps";
import { caProjection } from "@/lib/projections";
import { getEntity } from "@/lib/placeholder-data";
import { getEntityColorForDimension } from "@/lib/dimensions";
import {
  NEUTRAL_FILL,
  NEUTRAL_STROKE,
  type SetTooltip,
} from "@/lib/map-utils";
import { getCensusDivisionsByProvince } from "@/lib/census-division-data";
import { PROVINCE_NAME, type Dimension, type DimensionLens } from "@/types";

interface CanadaProvincesMapProps {
  onSelectEntity: (geoId: string) => void;
  onDoubleClickEntity?: (geoId: string) => void;
  selectedGeoId: string | null;
  setTooltip: SetTooltip;
  dimension?: Dimension;
  lens?: DimensionLens;
  /** When set, that province visually "lifts" before flipping to CensusDivisionMap. */
  drillingTo?: string | null;
}

const caProj = caProjection as unknown as ProjectionFunction;

// Local TopoJSON from Statistics Canada 2021 Census Boundary Files.
// Generated by scripts/geo/fetch-canada-geo.ts.
const PROVINCES_URL = "/geo/canada-provinces-2021.topo.json";

// PRUID → entity geoId mapping (ISO 3166-2:CA codes).
const PRUID_TO_GEOID: Record<string, string> = {
  "48": "CA-AB",
  "59": "CA-BC",
  "46": "CA-MB",
  "13": "CA-NB",
  "10": "CA-NL",
  "61": "CA-NT",
  "12": "CA-NS",
  "62": "CA-NU",
  "35": "CA-ON",
  "11": "CA-PE",
  "24": "CA-QC",
  "47": "CA-SK",
  "60": "CA-YT",
};

export default function CanadaProvincesMap({
  onSelectEntity,
  onDoubleClickEntity,
  selectedGeoId,
  setTooltip,
  dimension = "overall",
  lens = "zoning",
  drillingTo = null,
}: CanadaProvincesMapProps) {
  return (
    <div
      className="relative w-full h-full"
      onMouseMove={(e) =>
        setTooltip((current) =>
          current ? { ...current, x: e.clientX, y: e.clientY } : current,
        )
      }
      onMouseLeave={() => setTooltip(null)}
    >
      <ComposableMap
        width={960}
        height={600}
        projection={caProj}
        style={{ width: "100%", height: "100%", shapeRendering: "geometricPrecision" }}
      >
        <Geographies geography={PROVINCES_URL}>
          {({ geographies }) =>
            geographies
              .slice()
              .sort((a, b) => {
                const aId = String(a.id);
                const bId = String(b.id);
                const rank = (id: string) => {
                  const geoId = PRUID_TO_GEOID[id];
                  if (geoId === drillingTo) return 2;
                  if (geoId === selectedGeoId) return 1;
                  return 0;
                };
                return rank(aId) - rank(bId);
              })
              .map((geo) => {
              const pruid = String(geo.id);
              const geoId = PRUID_TO_GEOID[pruid];
              const name =
                (geo.properties.PRENAME as string) ??
                PROVINCE_NAME[pruid] ??
                pruid;

              if (!geoId) {
                return (
                  <Geography
                    key={geo.rsmKey}
                    geography={geo}
                    style={{
                      default: { fill: NEUTRAL_FILL, stroke: NEUTRAL_STROKE, strokeWidth: 0.5, outline: "none" },
                      hover: { fill: NEUTRAL_FILL, outline: "none" },
                      pressed: { fill: NEUTRAL_FILL, outline: "none" },
                    }}
                  />
                );
              }

              const ent = getEntity(geoId, "na");
              const isSelected = selectedGeoId === geoId;
              const fill = ent
                ? getEntityColorForDimension(ent, dimension, lens)
                : NEUTRAL_FILL;
              const stroke = isSelected ? "#FFFFFF" : NEUTRAL_STROKE;
              const strokeWidth = isSelected ? 3 : 0.8;
              const drillable = getCensusDivisionsByProvince(name).length > 0;
              const isDrillTarget = drillingTo === geoId;
              const isDrillOther = drillingTo !== null && !isDrillTarget;

              const base = {
                fill,
                stroke: isDrillTarget ? "#FFFFFF" : stroke,
                strokeWidth: isDrillTarget ? 5 : strokeWidth,
                strokeLinejoin: "round" as const,
                strokeLinecap: "round" as const,
                outline: "none",
                cursor: "pointer",
                transition:
                  "stroke 200ms, stroke-width 200ms, filter 380ms cubic-bezier(0.32,0.72,0,1), opacity 380ms ease, transform 380ms cubic-bezier(0.32,0.72,0,1)",
                transformBox: "fill-box" as const,
                transformOrigin: "center" as const,
                opacity: isDrillOther ? 0.12 : 1,
                transform: isDrillTarget ? "scale(1.45)" : undefined,
                filter: isDrillTarget
                  ? "drop-shadow(0 22px 40px rgba(0,0,0,0.35)) drop-shadow(0 6px 14px rgba(0,0,0,0.18)) brightness(1.06)"
                  : isSelected
                    ? "drop-shadow(0 4px 12px rgba(0,0,0,0.15))"
                    : undefined,
              };
              const hoverFilter = isSelected
                ? "drop-shadow(0 4px 12px rgba(0,0,0,0.18)) brightness(0.94)"
                : "brightness(0.94)";

              return (
                <Geography
                  key={geo.rsmKey}
                  geography={geo}
                  onMouseEnter={(e) =>
                    setTooltip({
                      x: e.clientX,
                      y: e.clientY,
                      label: name,
                      geoId,
                      region: "na",
                      drillable,
                    })
                  }
                  onMouseLeave={() => setTooltip(null)}
                  onClick={() => onSelectEntity(geoId)}
                  onDoubleClick={() => onDoubleClickEntity?.(geoId)}
                  style={{
                    default: base,
                    hover: { ...base, filter: hoverFilter },
                    pressed: base,
                  }}
                />
              );
            })}
        </Geographies>
      </ComposableMap>
    </div>
  );
}
